=== nneuer/presonus_schema_analysis/data/sample_output/schemas/FileExportReport.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "appFingerprint": {
            "type": "string",
            "examples": [
                "68CFA9B6D40E0BF02F410A66557A57E4",
                "68CFA9B6D40E0BF02F410A66557A57E4",
                "68CFA9B6D40E0BF02F410A66557A57E4",
                "877539B055AFBEC017ADA428CF808A52",
                "68CFA9B6D40E0BF02F410A66557A57E4",
                "68CFA9B6D40E0BF02F410A66557A57E4",
                "877539B055AFBEC017ADA428CF808A52"
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "appFlavor": {
            "type": "string",
            "examples": [
                "studioapp.retail",
                "studioapp.retail",
                "studioapp.retail",
                "studioapp.retail",
                "studioapp.retail",
                "studioapp.retail",
                "studioapp.retail"
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "appName": {
            "type": "string",
            "examples": [
                "Studio One",
                "Studio One",
                "Studio One",
                "Studio One",
                "Studio One",
                "Studio One",
                "Studio One"
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "appVersion": {
            "type": "string",
            "examples": [
                "6.1.1",
                "6.1.1",
                "6.1.1",
                "6.1.1",
                "6.1.1",
                "6.1.1",
                "6.1.1"
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "architecture": {
            "type": "string",
            "examples": [
                "x64",
                "x64",
                "x64",
                "ARM64",
                "x64",
                "x64",
                "x64"
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "buildNumber": {
            "type": "integer",
            "examples": [
                92984,
                92984,
                92984,
                92984,
                92984,
                92984,
                92984
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "lastTimestamp": {
            "type": "integer",
            "examples": [
                1682791200,
                0,
                0,
                0,
                0,
                1683223200,
                0
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "platform": {
            "type": "string",
            "examples": [
                "win",
                "win",
                "win",
                "mac",
                "win",
                "win",
                "mac"
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "timestamp": {
            "type": "integer",
            "examples": [
                1684362398,
                1684362402,
                1684362393,
                1684362465,
                1684362499,
                1684362592,
                1684362650
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "event": {
            "type": "string",
            "examples": [
                "FileExportReport",
                "FileExportReport",
                "FileExportReport",
                "FileExportReport",
                "FileExportReport",
                "FileExportReport",
                "FileExportReport"
            ],
            "matched_records": 7,
            "pct_of_records_matched": 100.0,
            "non_empty": 7,
            "non_empty_percent": 100.0
        },
        "exports": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string"
                    },
                    "count": {
                        "type": "integer"
                    },
                    "type": {
                        "type": "string"
                    }
                },
                "required": [
                    "context",
                    "count",
                    "type"
                ]
            },
            "examples": [
                [
                    {
                        "context": "DigitalRelease",
                        "count": 1,
                        "type": "mp3"
                    }
                ],
                [
                    {
                        "context": "Mixdown",
                        "count": 1,
                        "type": "wav"
                    }
                ],
                [
                    {
                        "context": "Mixdown",
                        "count": 1,
                        "type": "mp3"
                    }
                ],
                [
                    {
                        "context": "Mixdown",
                        "count": 5,
                        "type": "wav"
                    },
                    {
                        "context": "Stem",
                        "count": 2,
                        "type": "wav"
                    },
                    {
                        "context": "Mixdown",
                        "count": 5,
                        "type": "mp3"
                    }
                ]
            ],
            "matched_records": 4,
            "pct_of_records_matched": 57.142857142857146,
            "non_empty": 4,
            "non_empty_percent": 100.0
        }
    },
    "required": [
        "appFingerprint",
        "appFlavor",
        "appName",
        "appVersion",
        "architecture",
        "buildNumber",
        "event",
        "lastTimestamp",
        "platform",
        "timestamp"
    ]
}

=== nneuer/presonus_schema_analysis/data/sample_output/examples/FileExportReport_events_pretty.json
[
    {
        "appFingerprint": "68CFA9B6D40E0BF02F410A66557A57E4",
        "appFlavor": "studioapp.retail",
        "appName": "Studio One",
        "appVersion": "6.1.1",
        "architecture": "x64",
        "buildNumber": 92984,
        "lastTimestamp": 1682791200,
        "platform": "win",
        "timestamp": 1684362398,
        "event": "FileExportReport"
    },
    {
        "appFingerprint": "68CFA9B6D40E0BF02F410A66557A57E4",
        "appFlavor": "studioapp.retail",
        "appName": "Studio One",
        "appVersion": "6.1.1",
        "architecture": "x64",
        "buildNumber": 92984,
        "exports": [
            {
                "context": "DigitalRelease",
                "count": 1,
                "type": "mp3"
            }
        ],
        "lastTimestamp": 0,
        "platform": "win",
        "timestamp": 1684362402,
        "event": "FileExportReport"
    },
    {
        "appFingerprint": "68CFA9B6D40E0BF02F410A66557A57E4",
        "appFlavor": "studioapp.retail",
        "appName": "Studio One",
        "appVersion": "6.1.1",
        "architecture": "x64",
        "buildNumber": 92984,
        "lastTimestamp": 0,
        "platform": "win",
        "timestamp": 1684362393,
        "event": "FileExportReport"
    },
    {
        "appFingerprint": "877539B055AFBEC017ADA428CF808A52",
        "appFlavor": "studioapp.retail",
        "appName": "Studio One",
        "appVersion": "6.1.1",
        "architecture": "ARM64",
        "buildNumber": 92984,
        "lastTimestamp": 0,
        "platform": "mac",
        "timestamp": 1684362465,
        "event": "FileExportReport"
    },
    {
        "appFingerprint": "68CFA9B6D40E0BF02F410A66557A57E4",
        "appFlavor": "studioapp.retail",
        "appName": "Studio One",
        "appVersion": "6.1.1",
        "architecture": "x64",
        "buildNumber": 92984,
        "exports": [
            {
                "context": "Mixdown",
                "count": 1,
                "type": "wav"
            }
        ],
        "lastTimestamp": 0,
        "platform": "win",
        "timestamp": 1684362499,
        "event": "FileExportReport"
    },
    {
        "appFingerprint": "68CFA9B6D40E0BF02F410A66557A57E4",
        "appFlavor": "studioapp.retail",
        "appName": "Studio One",
        "appVersion": "6.1.1",
        "architecture": "x64",
        "buildNumber": 92984,
        "exports": [
            {
                "context": "Mixdown",
                "count": 1,
                "type": "mp3"
            }
        ],
        "lastTimestamp": 1683223200,
        "platform": "win",
        "timestamp": 1684362592,
        "event": "FileExportReport"
    },
    {
        "appFingerprint": "877539B055AFBEC017ADA428CF808A52",
        "appFlavor": "studioapp.retail",
        "appName": "Studio One",
        "appVersion": "6.1.1",
        "architecture": "x64",
        "buildNumber": 92984,
        "exports": [
            {
                "context": "Mixdown",
                "count": 5,
                "type": "wav"
            },
            {
                "context": "Stem",
                "count": 2,
                "type": "wav"
            },
            {
                "context": "Mixdown",
                "count": 5,
                "type": "mp3"
            }
        ],
        "lastTimestamp": 0,
        "platform": "mac",
        "timestamp": 1684362650,
        "event": "FileExportReport"
    }
]
